### ISSUE TITLE
Problem met installeren van payment module

### ISSUE THREAD

**Issue by robinpoept** [0100Dev/WHMCS-Mollie-Payments#67]
Goedendag,
Als ik de module upload in mijn modules/gateways en vervolgens in whmcs naar betaalmethodes ga krijg ik een error en zie ik het volgende. iemand weet wat hier het probleem van is?

Image van wat ik zie: 
![Screenshot_1](https://user-images.githubusercontent.com/26725451/90576169-b5991b00-e1bd-11ea-86cc-661547421a95.png)

**Comment by tamerciaga** [comment]
Het probleem is dat je ons alleen een screenshot geeft zonder enige logs.

**Comment by VORD-Sven** [comment]
zet in configuration.php aan het einde het volgende.

`$display_errors = '1';`

om gedetailleerde errors te zien. deze ook weer weg halen als je klaar bent.

**Comment by Wouter0100** [comment]
Bedankt voor de reacties. Gezien de error heb je de instructies niet goed gevolgd en mis je dus de vendor folder. Download de _juiste_ build/file, zoals aangegeven in de instructies - en dan zal 't werken :). 

Duplicate #44
