### ISSUE TITLE
In the download i miss the folder "vendor"

### ISSUE THREAD

**Issue by lutjebroeker** [0100Dev/WHMCS-Mollie-Payments#69]
I wanted to update the code but i get an error from WHMCS "OOOPS.."

I hit the download button here at github.
Unzipped and uploaded all in the files in the "src"  folder into the remote whmcs folder "gateways"
Opened the website and i got an WHMCS "OOOPS.."error.

When I compared the downloaded folder with the old folder.
I noticed that there was no folder named "vendor"

When uploading that missing folder from the download zip everything worked again!
Soo i think that folder is missing here in the github download zip

**Comment by Wouter0100** [comment]
Duplicate of #44
