### ISSUE TITLE
Addon werkt niet wanneer bestanden zijn geupload.

### ISSUE THREAD

**Issue by Sundeep-deJongh** [0100Dev/WHMCS-Mollie-Payments#74]
Zodra je de bestanden upload in de gateaways folder,
en je dan naar "betaalmethodes" gaat in WHMCS dan krijg je een errorpage.
maar zodra je de bestanden verwijderd dan doet alles het weer.

**Comment by Wouter0100** [comment]
Heb je de handleiding volledig gevolgd? Lijkt op een duplicate van #44.
