### ISSUE TITLE
Hulp nodig

### ISSUE THREAD

**Issue by Sundeep-deJongh** [0100Dev/WHMCS-Mollie-Payments#78]
Ik zou graag hulp willen met het instellen van deze betaalmethode het lukt me niet echt,
Wanneer ik de bestanden upload en ik dan naar "betaalmethodes" in WHMCS gaat en ik mijn API key van mollie bij bijvoorbeeld IDEAL mollie zet en ik ga testen voor test betaling werkt het niet.

**Comment by Wouter0100** [comment]
Meer informatie is, anders kunnen we lastig aanwijzgne wat het probleem is. Wanneer je premium support wilt, kan je contact met 0100Dev opnemen zoals vermeld in de README. Dat is wel tegen betaling.
