### ISSUE TITLE
Payment Error Invalid Value

### ISSUE THREAD

**Issue by crupsos** [0100Dev/WHMCS-Mollie-Payments#79]
I always get an error when paying. I buy a service and try to pay via paypal (Mollie) and get the error, please help.

![image](https://user-images.githubusercontent.com/58829732/107506365-47e31000-6b9e-11eb-97c2-327c94d44515.png)

**Comment by Wouter0100** [comment]
Which currencies are configured in your WHMCS? Could you share a screenshot of that page?
