### ISSUE TITLE
Vendor issue WHMCS 8.1.3 [SOLVED]

### ISSUE THREAD

**Issue by trickbaze** [0100Dev/WHMCS-Mollie-Payments#83]
Hallo,

Zou iemand mij uit de brand kunnen helpen ik krijg deze error namelijk wanneer ik alle stappen heb gevolgd uit de installatie lijst.

Whoops\Exception\ErrorException: require_once(): Failed opening required '/home/directnh/public_html/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/directnh/public_html/modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /home/directnh/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home/directnh/...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}

Alvast bedankt.

**Comment by dspaan** [comment]
Wat is de oplossing? Ik heb zojuist de addon voor het eerst gedownload en ik krijg ook deze error.

**Comment by dspaan** [comment]
Never mind, ik moest dus payments.zip downloaden en niet payments master.

**Comment by Wouter0100** [comment]
#44
