### ISSUE TITLE
expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by dspaan** [0100Dev/WHMCS-Mollie-Payments#84]
We are using an older version of WHMCS for one of our installs, version 7.4.2

We get this error when testing the mollie creditcard gateway.

ParseError: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /modules/gateways/mollie/vendor/guzzlehttp/guzzle/src/Client.php:202

**Comment by Wouter0100** [comment]
Please read the release docs to check with PHP version is supported. This is as expected.
