### ISSUE TITLE
Mollie payments does not work

### ISSUE THREAD

**Issue by FinnXDeezzz** [0100Dev/WHMCS-Mollie-Payments#95]
Hello!

I have been trying to install WHMCS Mollie payments for a few days, but everytime when i acces the payment gateaway configuration page I get an error message. Can someone help me?

Error message:
`Whoops\Exception\ErrorException: require_once(): Failed opening required '/home2/colornod/domains/colornode.nl/public_html/modules/gateways/mollie/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /home2/colornod/domains/colornode.nl/public_html/modules/gateways/mollie/mollie.php:3
Stack trace:
#0 /home2/colornod/domains/colornode.nl/public_html/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(64, 'require_once():...', '/home2/colornod...', 3)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}`

WHMCS version: 8.3.2
PHP version: 7.4

**Comment by Wouter0100** [comment]
#44
