### ISSUE TITLE
Not working on WHMCS 8.4/8.5

### ISSUE THREAD

**Issue by WolfTM** [0100Dev/WHMCS-Mollie-Payments#97]
I've so far only tested it on WHMCS 8.4 and 8.5.
But when you transfer all files to the directory nothing happens.
The module doesn't show up, and WHMCS acts like nothing has changed at all.

I did do the steps from Readme,
Nothing of errors are happening or being logged.

Just after upload nothing happens.

**Comment by Wouter0100** [comment]
Did you transfer the files to the correct directory? Could you please elaborate on the steps you're taking?

**Comment by WolfTM** [comment]
Hey Wouter,

Thanks for your reply. I've seem to have solved the issue.
We've restarted our webserver and now it all works fine.
I suppose I'll never know why it didn't work straight away but at least it is solved.

Thank you for your time.
